baseURL = 'https://numan947.github.io/'
languageCode = 'en-us'
title = 'S. M. Hasan'
theme = "hugo-theme-monochrome"
publishDir = "docs"


[params]
  author = "Your Name"
  description = "A brief description of your site"
  showReadingTime = true
  dateFormat = "January 2, 2006"
  enableComments = true
  enable_site_search = false
  math = true  

markup.goldmark.parser.attribute.block = true
markup.goldmark.parser.wrapStandAloneImageWithinParagraph = true

[menu]
  [[menu.navbar]]
    name = "About Me"
    url = "/about/"
    weight = 10

  [[menu.navbar]]
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.navbar]]
    name = "Publications"
    url = "/publications/"
    weight = 30

  [[menu.navbar]]
    name = "Bits, Bytes & Life"
    url = "/posts/"
    weight = 40

  # [[menu.navbar]]
  #   name = "Teaching"
  #   url = "/teaching/"
  #   weight = 50


[taxonomies]
  tag = "tags"
  category = "categories"


